# Generated by Django 5.0.1 on 2024-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='text_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
