# Generated by Django 5.0.4 on 2024-05-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/profilepic.png', null=True, upload_to='profile_pics'),
        ),
    ]
